/* SARD BD — Shared Courses Data
   Used by: training.html (card grid) + course.html (detail page)
*/
var COURSES = [
  // ── RESEARCH METHODS ─────────────────────────────────────────────────
  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-search',
    title:'Introduction to Research & Identifying the Research Problem',
    titleBn:'গবেষণার ভূমিকা ও সমস্যা চিহ্নিতকরণ',
    desc:'Foundations of scientific inquiry, problem formulation, objectives, and research questions.',
    descBn:'বৈজ্ঞানিক অনুসন্ধানের ভিত্তি, সমস্যা প্রণয়ন, উদ্দেশ্য ও গবেষণা প্রশ্ন নির্ধারণ।',
    learn:['Understand the scientific method','Identify a researchable problem','Write SMART objectives','Formulate research questions','Distinguish types of research','Conduct a gap analysis'],
    learnBn:['বৈজ্ঞানিক পদ্ধতি বোঝা','গবেষণাযোগ্য সমস্যা চিহ্নিত করা','SMART উদ্দেশ্য লেখা','গবেষণা প্রশ্ন প্রণয়ন','গবেষণার ধরন পার্থক্য করা','গ্যাপ বিশ্লেষণ করা'],
    audience:['Students & early researchers','Healthcare professionals','NGO programme staff','Policy makers'],
    audienceBn:['শিক্ষার্থী ও নতুন গবেষক','স্বাস্থ্যসেবা পেশাদার','NGO কর্মসূচি কর্মী','নীতিনির্ধারক'],
    duration:'1 Day', badge:'popular', rating:'4.9', enrolled:'320+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-journals',
    title:'Literature Review & Its Importance in Research',
    titleBn:'সাহিত্য পর্যালোচনা ও গবেষণায় গুরুত্ব',
    desc:'Systematic search strategies, critical appraisal, citation management, and synthesizing evidence.',
    descBn:'সুশৃঙ্খল অনুসন্ধান কৌশল, সমালোচনামূলক মূল্যায়ন এবং প্রমাণ সংশ্লেষণ।',
    learn:['Search PubMed, Google Scholar, Cochrane','Use PRISMA flowchart','Critically appraise articles','Manage citations (Mendeley/Zotero)','Synthesize evidence from multiple sources','Write a structured literature review'],
    learnBn:['PubMed ও Google Scholar সার্চ','PRISMA ফ্লোচার্ট ব্যবহার','আর্টিকেল সমালোচনামূলকভাবে মূল্যায়ন','সাইটেশন ম্যানেজমেন্ট (Mendeley/Zotero)','একাধিক উৎস থেকে প্রমাণ সংশ্লেষণ','কাঠামোগত সাহিত্য পর্যালোচনা লেখা'],
    audience:['Graduate & postgraduate students','Faculty members','Researchers & scientists','Medical professionals'],
    audienceBn:['স্নাতক ও স্নাতকোত্তর শিক্ষার্থী','শিক্ষক ও অধ্যাপক','গবেষক ও বিজ্ঞানী','চিকিৎসা পেশাদার'],
    duration:'1 Day', badge:'', rating:'4.8', enrolled:'280+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-diagram-3',
    title:'Research Design',
    titleBn:'গবেষণা নকশা',
    desc:'Exploratory, descriptive, experimental & observational study designs — choosing the right framework.',
    descBn:'এক্সপ্লোরেটরি, বর্ণনামূলক, পরীক্ষামূলক ও পর্যবেক্ষণমূলক স্টাডি ডিজাইন।',
    learn:['Differentiate study designs (RCT, cohort, case-control)','Select appropriate design for your question','Understand internal & external validity','Design a cross-sectional study','Prepare a study protocol','Control for confounding'],
    learnBn:['স্টাডি ডিজাইন পার্থক্য (RCT, cohort, case-control)','প্রশ্ন অনুযায়ী সঠিক ডিজাইন নির্বাচন','অভ্যন্তরীণ ও বাহ্যিক বৈধতা বোঝা','ক্রস-সেকশনাল স্টাডি ডিজাইন','স্টাডি প্রোটোকল প্রস্তুতি','কনফাউন্ডিং নিয়ন্ত্রণ'],
    audience:['Researchers & academics','Medical & public health graduates','Thesis & dissertation students','Programme evaluators'],
    audienceBn:['গবেষক ও শিক্ষাবিদ','চিকিৎসা ও জনস্বাস্থ্য স্নাতক','থিসিস ও ডিসার্টেশন শিক্ষার্থী','কর্মসূচি মূল্যায়নকারী'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'260+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-people',
    title:'Sampling & Sample Size Determination',
    titleBn:'নমুনায়ন ও নমুনা আকার নির্ধারণ',
    desc:'Probability and non-probability sampling, power analysis, and sample size calculators.',
    descBn:'সম্ভাবনাভিত্তিক ও অ-সম্ভাবনাভিত্তিক নমুনায়ন এবং পাওয়ার বিশ্লেষণ।',
    learn:['Random, stratified, cluster, systematic sampling','Purposive and snowball sampling','Calculate sample size (n formula)','Use G*Power software','Understand sampling bias & error','Prepare sampling frame'],
    learnBn:['র‍্যান্ডম, স্তরীভূত, ক্লাস্টার নমুনায়ন','পার্পোসিভ ও স্নোবল নমুনায়ন','নমুনা আকার গণনা','G*Power সফটওয়্যার ব্যবহার','স্যাম্পলিং বায়াস ও ত্রুটি বোঝা','স্যাম্পলিং ফ্রেম তৈরি'],
    audience:['Thesis & dissertation students','Public health researchers','Clinical trial researchers','Data scientists'],
    audienceBn:['থিসিস শিক্ষার্থী','জনস্বাস্থ্য গবেষক','ক্লিনিক্যাল ট্রায়াল গবেষক','ডেটা বিজ্ঞানী'],
    duration:'1 Day', badge:'', rating:'4.8', enrolled:'240+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-clipboard2-data',
    title:'Data Collection Methods',
    titleBn:'তথ্য সংগ্রহ পদ্ধতি',
    desc:'Survey design, interviews, focus groups, observation, and digital data collection tools.',
    descBn:'সমীক্ষা ডিজাইন, সাক্ষাৎকার, ফোকাস গ্রুপ এবং ডিজিটাল ডেটা সংগ্রহ।',
    learn:['Design a questionnaire (open/closed)','Conduct structured interviews','Facilitate focus group discussions','Use KoBoToolbox / ODK for digital collection','Observe and record field data','Pilot test a data collection tool'],
    learnBn:['প্রশ্নমালা ডিজাইন (খোলা/বন্ধ)','কাঠামোগত সাক্ষাৎকার পরিচালনা','ফোকাস গ্রুপ আলোচনা সহায়তা','KoBoToolbox / ODK ব্যবহার','ফিল্ড ডেটা পর্যবেক্ষণ ও রেকর্ড','ডেটা সংগ্রহ টুল পাইলট টেস্ট'],
    audience:['Field researchers & enumerators','NGO monitoring staff','Public health professionals','Survey coordinators'],
    audienceBn:['ফিল্ড গবেষক ও গণনাকারী','NGO মনিটরিং কর্মী','জনস্বাস্থ্য পেশাদার','সমীক্ষা সমন্বয়কারী'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'250+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-rulers',
    title:'Measurement & Scaling',
    titleBn:'পরিমাপ ও স্কেলিং',
    desc:'Validity, reliability, Likert scales, index construction, and operationalizing variables.',
    descBn:'বৈধতা, নির্ভরযোগ্যতা, লিকার্ট স্কেল এবং ভেরিয়েবল অপারেশনালাইজেশন।',
    learn:['Understand levels of measurement','Construct Likert & semantic differential scales','Test content, construct, criterion validity','Calculate Cronbach alpha for reliability','Operationalize abstract concepts','Build composite indices'],
    learnBn:['পরিমাপের স্তর বোঝা','লিকার্ট ও সিম্যান্টিক স্কেল তৈরি','বিষয়বস্তু, কনস্ট্রাক্ট, মানদণ্ড বৈধতা পরীক্ষা','ক্রোনবাক আলফা গণনা','বিমূর্ত ধারণা অপারেশনালাইজ করা','যৌগিক সূচক তৈরি'],
    audience:['Questionnaire designers','Survey methodologists','Psychometric researchers','Programme evaluators'],
    audienceBn:['প্রশ্নমালা ডিজাইনার','সমীক্ষা পদ্ধতিবিদ','সাইকোমেট্রিক গবেষক','কর্মসূচি মূল্যায়নকারী'],
    duration:'Half Day', badge:'', rating:'4.6', enrolled:'190+', color:'#1565c0' },

  { cat:'research', catLabel:'Research Methods', catClass:'cat-research', icon:'bi-question-diamond',
    title:'Hypothesis',
    titleBn:'অনুকল্প',
    desc:'Formulating null and alternative hypotheses, significance levels, and Type I/II errors.',
    descBn:'শূন্য ও বিকল্প অনুকল্প প্রণয়ন, উল্লেখযোগ্যতা স্তর এবং টাইপ I/II ত্রুটি।',
    learn:['Write null (H₀) and alternative (H₁) hypotheses','Understand p-value and significance levels','Distinguish Type I and Type II errors','Choose one-tailed vs two-tailed tests','Link hypothesis to study objectives','Interpret statistical test results'],
    learnBn:['H₀ এবং H₁ অনুকল্প লেখা','p-value ও উল্লেখযোগ্যতা স্তর বোঝা','টাইপ I ও II ত্রুটি পার্থক্য করা','এক-পুচ্ছ বনাম দ্বি-পুচ্ছ পরীক্ষা নির্বাচন','অনুকল্পকে উদ্দেশ্যের সাথে সংযুক্ত করা','পরিসংখ্যান পরীক্ষার ফলাফল ব্যাখ্যা'],
    audience:['Statistics students','Biomedical researchers','Clinical investigators','Thesis students'],
    audienceBn:['পরিসংখ্যান শিক্ষার্থী','বায়োমেডিক্যাল গবেষক','ক্লিনিক্যাল তদন্তকারী','থিসিস শিক্ষার্থী'],
    duration:'Half Day', badge:'', rating:'4.7', enrolled:'210+', color:'#1565c0' },

  // ── DATA ANALYSIS ─────────────────────────────────────────────────────
  { cat:'data', catLabel:'Data Analysis', catClass:'cat-data', icon:'bi-bar-chart-steps',
    title:'Data Processing & Analysis using SPSS',
    titleBn:'SPSS দিয়ে ডেটা প্রক্রিয়াকরণ ও বিশ্লেষণ',
    desc:'Data entry, cleaning, descriptive statistics, t-tests, ANOVA, regression in SPSS.',
    descBn:'ডেটা এন্ট্রি, ক্লিনিং, বর্ণনামূলক পরিসংখ্যান, t-test, ANOVA এবং রিগ্রেশন।',
    learn:['Navigate SPSS interface & data view','Enter and clean data','Run descriptive statistics & frequencies','Perform t-tests, chi-square, ANOVA','Conduct linear & logistic regression','Interpret output tables & export results'],
    learnBn:['SPSS ইন্টারফেস নেভিগেট করা','ডেটা এন্ট্রি ও ক্লিনিং','বর্ণনামূলক পরিসংখ্যান ও ফ্রিকোয়েন্সি','t-test, chi-square, ANOVA চালানো','লিনিয়ার ও লজিস্টিক রিগ্রেশন','আউটপুট ব্যাখ্যা ও ফলাফল রপ্তানি'],
    audience:['Health & social science researchers','Medical graduates','MPH students','NGO evaluation staff'],
    audienceBn:['স্বাস্থ্য ও সামাজিক বিজ্ঞান গবেষক','চিকিৎসা স্নাতক','MPH শিক্ষার্থী','NGO মূল্যায়ন কর্মী'],
    duration:'2 Days', badge:'popular', rating:'4.9', enrolled:'410+', color:'#6a1b9a' },

  { cat:'data', catLabel:'Data Analysis', catClass:'cat-data', icon:'bi-code-square',
    title:'Data Processing & Analysis using R',
    titleBn:'R দিয়ে ডেটা প্রক্রিয়াকরণ ও বিশ্লেষণ',
    desc:'R programming, tidyverse, ggplot2 visualization, and statistical modelling in R.',
    descBn:'R প্রোগ্রামিং, tidyverse, ggplot2 ভিজ্যুয়ালাইজেশন এবং পরিসংখ্যান মডেলিং।',
    learn:['Install R & RStudio','Write basic R scripts','Manipulate data with tidyverse (dplyr/tidyr)','Create visualizations with ggplot2','Run statistical tests in R','Generate reproducible reports (R Markdown)'],
    learnBn:['R ও RStudio ইনস্টল করা','মৌলিক R স্ক্রিপ্ট লেখা','tidyverse দিয়ে ডেটা ম্যানিপুলেশন','ggplot2 দিয়ে ভিজ্যুয়ালাইজেশন','R-এ পরিসংখ্যান পরীক্ষা চালানো','R Markdown দিয়ে রিপোর্ট তৈরি'],
    audience:['Epidemiologists & biostatisticians','Data scientists in health','Academic researchers','MPH/PhD students'],
    audienceBn:['মহামারীবিদ ও বায়োস্ট্যাটিস্টিশিয়ান','স্বাস্থ্যখাতে ডেটা বিজ্ঞানী','একাডেমিক গবেষক','MPH/PhD শিক্ষার্থী'],
    duration:'2 Days', badge:'new', rating:'4.8', enrolled:'290+', color:'#6a1b9a' },

  { cat:'data', catLabel:'Data Analysis', catClass:'cat-data', icon:'bi-cpu',
    title:'Data Processing & Analysis using Stata',
    titleBn:'Stata দিয়ে ডেটা প্রক্রিয়াকরণ ও বিশ্লেষণ',
    desc:'Stata commands, data management, regression analysis, and panel data modelling.',
    descBn:'Stata কমান্ড, ডেটা ম্যানেজমেন্ট, রিগ্রেশন এবং প্যানেল ডেটা মডেলিং।',
    learn:['Navigate Stata do-files & command line','Import & manage datasets','Run tabulations & summary statistics','Perform regression (OLS, logit, probit)','Analyse panel and longitudinal data','Write Stata do-files for reproducibility'],
    learnBn:['Stata do-file ও কমান্ড লাইন ব্যবহার','ডেটাসেট ইম্পোর্ট ও ম্যানেজ করা','ট্যাবুলেশন ও সারসংক্ষেপ পরিসংখ্যান','রিগ্রেশন (OLS, logit, probit) চালানো','প্যানেল ও দীর্ঘমেয়াদী ডেটা বিশ্লেষণ','পুনরুৎপাদনযোগ্যতার জন্য do-file লেখা'],
    audience:['Economics & development researchers','Health policy analysts','Clinical researchers','Postgraduate students'],
    audienceBn:['অর্থনীতি ও উন্নয়ন গবেষক','স্বাস্থ্য নীতি বিশ্লেষক','ক্লিনিক্যাল গবেষক','স্নাতকোত্তর শিক্ষার্থী'],
    duration:'2 Days', badge:'', rating:'4.7', enrolled:'200+', color:'#6a1b9a' },

  { cat:'data', catLabel:'Data Analysis', catClass:'cat-data', icon:'bi-graph-up',
    title:'Data Presentation',
    titleBn:'তথ্য উপস্থাপনা',
    desc:'Tables, charts, infographics, and effective scientific data visualization techniques.',
    descBn:'টেবিল, চার্ট, ইনফোগ্রাফিক এবং বৈজ্ঞানিক ডেটা ভিজ্যুয়ালাইজেশন কৌশল।',
    learn:['Design APA/Vancouver-style tables','Choose the right chart type for your data','Create bar, line, scatter, pie charts','Build infographics with Canva/PowerPoint','Follow journal figure formatting guidelines','Present data in conference slides'],
    learnBn:['APA/Vancouver স্টাইল টেবিল ডিজাইন','ডেটার জন্য সঠিক চার্ট নির্বাচন','বার, লাইন, স্ক্যাটার, পাই চার্ট তৈরি','Canva/PowerPoint দিয়ে ইনফোগ্রাফিক','জার্নাল ফিগার ফরম্যাটিং নির্দেশিকা','কনফারেন্স স্লাইডে ডেটা উপস্থাপনা'],
    audience:['All researchers & writers','Conference presenters','Report writers','Public health communicators'],
    audienceBn:['সকল গবেষক ও লেখক','কনফারেন্স উপস্থাপক','রিপোর্ট লেখক','জনস্বাস্থ্য যোগাযোগকারী'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'230+', color:'#6a1b9a' },

  // ── WRITING & PUBLICATION ─────────────────────────────────────────────
  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-shield-check',
    title:'Research Ethics',
    titleBn:'গবেষণা নৈতিকতা',
    desc:'Informed consent, confidentiality, IRB processes, plagiarism, and research integrity.',
    descBn:'অবহিত সম্মতি, গোপনীয়তা, IRB প্রক্রিয়া, প্ল্যাজিয়ারিজম এবং গবেষণা অখণ্ডতা।',
    learn:['Understand Belmont Report principles','Obtain informed consent','Submit to Institutional Review Board (IRB)','Protect participant confidentiality','Avoid plagiarism (use Turnitin/iThenticate)','Understand authorship and conflict of interest'],
    learnBn:['বেলমন্ট রিপোর্ট নীতি বোঝা','অবহিত সম্মতি প্রাপ্তি','IRB-এ জমা দেওয়া','অংশগ্রহণকারীর গোপনীয়তা রক্ষা','প্ল্যাজিয়ারিজম এড়ানো','লেখকত্ব ও স্বার্থের দ্বন্দ্ব বোঝা'],
    audience:['All researchers','Students conducting human research','IRB committee members','Grant applicants'],
    audienceBn:['সকল গবেষক','মানব গবেষণায় শিক্ষার্থী','IRB কমিটি সদস্য','অনুদান আবেদনকারী'],
    duration:'1 Day', badge:'', rating:'4.8', enrolled:'280+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-file-earmark-check',
    title:'Report Writing',
    titleBn:'রিপোর্ট লেখা',
    desc:'Structure of research reports, executive summaries, technical writing, and donor report formats.',
    descBn:'গবেষণা রিপোর্টের কাঠামো, এক্সিকিউটিভ সারসংক্ষেপ এবং ডোনার রিপোর্ট ফরম্যাট।',
    learn:['Structure an academic/technical report','Write a concise executive summary','Use active voice in scientific writing','Format WHO, UNICEF, USAID donor reports','Cite sources in Vancouver/APA style','Review and edit for clarity and conciseness'],
    learnBn:['একাডেমিক/প্রযুক্তিগত রিপোর্টের কাঠামো','সংক্ষিপ্ত এক্সিকিউটিভ সারসংক্ষেপ লেখা','বৈজ্ঞানিক লেখায় সক্রিয় কণ্ঠস্বর ব্যবহার','WHO, UNICEF, USAID ডোনার রিপোর্ট ফরম্যাট','ভ্যাঙ্কুভার/APA স্টাইলে উদ্ধৃতি','স্পষ্টতার জন্য পর্যালোচনা ও সম্পাদনা'],
    audience:['NGO programme officers','Government health staff','Project managers','Research assistants'],
    audienceBn:['NGO কর্মসূচি কর্মকর্তা','সরকারি স্বাস্থ্য কর্মী','প্রকল্প ব্যবস্থাপক','গবেষণা সহকারী'],
    duration:'1 Day', badge:'', rating:'4.6', enrolled:'220+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-journal-text',
    title:'Qualitative & Quantitative Research',
    titleBn:'গুণগত ও পরিমাণগত গবেষণা',
    desc:'Paradigm differences, mixed-methods designs, thematic analysis, and triangulation.',
    descBn:'প্যারাডাইম পার্থক্য, মিশ্র পদ্ধতি ডিজাইন, থিম্যাটিক বিশ্লেষণ এবং ট্রায়াঙ্গুলেশন।',
    learn:['Distinguish positivist vs interpretivist paradigms','Design a mixed-methods study','Conduct thematic analysis of qualitative data','Perform content and narrative analysis','Ensure rigor: credibility, transferability','Triangulate data from multiple sources'],
    learnBn:['পজিটিভিস্ট বনাম ইন্টারপ্রিটিভিস্ট প্যারাডাইম','মিশ্র পদ্ধতি স্টাডি ডিজাইন','গুণগত ডেটার থিম্যাটিক বিশ্লেষণ','বিষয়বস্তু ও ন্যারেটিভ বিশ্লেষণ','বিশ্বাসযোগ্যতা ও স্থানান্তরযোগ্যতা নিশ্চিত করা','একাধিক উৎস থেকে ডেটা ট্রায়াঙ্গুলেশন'],
    audience:['Social science researchers','Health researchers','Evaluators & assessors','Postgraduate students'],
    audienceBn:['সামাজিক বিজ্ঞান গবেষক','স্বাস্থ্য গবেষক','মূল্যায়নকারী','স্নাতকোত্তর শিক্ষার্থী'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'250+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-file-earmark-medical',
    title:'Protocol Writing (Thesis or Dissertation)',
    titleBn:'প্রোটোকল লেখা (থিসিস বা ডিসার্টেশন)',
    desc:'Writing research proposals, ethical clearance applications, and academic protocols.',
    descBn:'গবেষণা প্রস্তাব, নৈতিক অনুমোদন আবেদন এবং একাডেমিক প্রোটোকল লেখা।',
    learn:['Write a full research protocol from scratch','Develop study objectives and hypotheses','Prepare methodology and data management plan','Write IRB/ethical clearance application','Format references and appendices','Defend your protocol before a panel'],
    learnBn:['শূন্য থেকে পূর্ণ গবেষণা প্রোটোকল লেখা','উদ্দেশ্য ও অনুকল্প তৈরি','পদ্ধতি ও ডেটা ম্যানেজমেন্ট পরিকল্পনা','IRB/নৈতিক অনুমোদন আবেদন লেখা','রেফারেন্স ও পরিশিষ্ট ফরম্যাট করা','প্যানেলের সামনে প্রোটোকল রক্ষা করা'],
    audience:['Thesis/dissertation students','Residency & fellowship trainees','Early career researchers','Academic supervisors'],
    audienceBn:['থিসিস/ডিসার্টেশন শিক্ষার্থী','রেসিডেন্সি ও ফেলোশিপ প্রশিক্ষণার্থী','প্রারম্ভিক গবেষক','একাডেমিক সুপারভাইজার'],
    duration:'2 Days', badge:'popular', rating:'4.9', enrolled:'370+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-award',
    title:'Research Grant Writing',
    titleBn:'গবেষণা অনুদান লেখা',
    desc:'NIH, WHO, and JICA grant formats, budget preparation, and winning proposal strategies.',
    descBn:'NIH, WHO এবং JICA অনুদান ফরম্যাট, বাজেট প্রস্তুতি এবং সফল প্রস্তাব কৌশল।',
    learn:['Understand NIH, WHO, JICA grant structures','Write a compelling specific aims page','Develop a realistic budget & justification','Frame your significance & innovation','Write preliminary data sections','Avoid common grant rejection pitfalls'],
    learnBn:['NIH, WHO, JICA অনুদানের কাঠামো বোঝা','আকর্ষণীয় specific aims পেজ লেখা','বাস্তবসম্মত বাজেট ও যুক্তি তৈরি','তাৎপর্য ও উদ্ভাবন তুলে ধরা','প্রাথমিক ডেটা অধ্যায় লেখা','সাধারণ প্রত্যাখ্যানের কারণ এড়ানো'],
    audience:['Faculty & senior researchers','Public health professionals','NGO directors & programme leads','PhD students'],
    audienceBn:['শিক্ষক ও সিনিয়র গবেষক','জনস্বাস্থ্য পেশাদার','NGO পরিচালক ও কর্মসূচি নেতা','PhD শিক্ষার্থী'],
    duration:'2 Days', badge:'featured', rating:'4.9', enrolled:'310+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-newspaper',
    title:'How to Write a Journal Article',
    titleBn:'জার্নাল আর্টিকেল কীভাবে লিখবেন',
    desc:'IMRAD structure, title and abstract crafting, cover letter, submission, and revision strategy.',
    descBn:'IMRAD কাঠামো, শিরোনাম ও বিমূর্ততা, কভার লেটার, জমা ও সংশোধন কৌশল।',
    learn:['Apply IMRAD (Intro-Methods-Results-Discussion)','Write a title and structured abstract','Select the right journal (scope, impact factor)','Write a professional cover letter','Respond to peer reviewer comments','Navigate manuscript management systems'],
    learnBn:['IMRAD কাঠামো প্রয়োগ','শিরোনাম ও কাঠামোগত বিমূর্ততা লেখা','সঠিক জার্নাল নির্বাচন','পেশাদার কভার লেটার লেখা','পিয়ার রিভিউয়ার মন্তব্যের জবাব দেওয়া','ম্যানাস্ক্রিপ্ট ম্যানেজমেন্ট সিস্টেম ব্যবহার'],
    audience:['Researchers with completed studies','Clinicians seeking publication','PhD & postdoc researchers','JARD journal contributors'],
    audienceBn:['সম্পন্ন গবেষণা সহ গবেষক','প্রকাশনা চাওয়া চিকিৎসক','PhD ও পোস্টডক গবেষক','JARD জার্নাল অবদানকারী'],
    duration:'1 Day', badge:'popular', rating:'4.9', enrolled:'420+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-pencil-square',
    title:'Manuscript Writing',
    titleBn:'পাণ্ডুলিপি লেখা',
    desc:'Hands-on manuscript preparation from raw data to submission-ready draft.',
    descBn:'কাঁচা ডেটা থেকে জমা দেওয়ার উপযোগী খসড়া পর্যন্ত পাণ্ডুলিপি প্রস্তুতি।',
    learn:['Convert a thesis chapter into a manuscript','Write each section (Intro, Methods, Results, Discussion)','Follow journal author guidelines strictly','Use reporting checklists (CONSORT, STROBE, PRISMA)','Format references with a reference manager','Prepare supplementary materials & figures'],
    learnBn:['থিসিস অধ্যায়কে পাণ্ডুলিপিতে রূপান্তর','প্রতিটি অধ্যায় (Intro, Methods, Results, Discussion) লেখা','জার্নালের লেখক নির্দেশিকা অনুসরণ','রিপোর্টিং চেকলিস্ট ব্যবহার','রেফারেন্স ম্যানেজার দিয়ে রেফারেন্স ফরম্যাট','সাপ্লিমেন্টারি উপকরণ প্রস্তুতি'],
    audience:['Researchers with raw data','Thesis & dissertation authors','Medical officers & specialists','Academic writers'],
    audienceBn:['কাঁচা ডেটা সহ গবেষক','থিসিস ও ডিসার্টেশন লেখক','চিকিৎসা কর্মকর্তা ও বিশেষজ্ঞ','একাডেমিক লেখক'],
    duration:'2 Days', badge:'', rating:'4.8', enrolled:'350+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-easel2',
    title:'Poster Presentation',
    titleBn:'পোস্টার উপস্থাপনা',
    desc:'Designing research posters, key message framing, conference presentation skills.',
    descBn:'গবেষণা পোস্টার ডিজাইন, মূল বার্তা তৈরি এবং কনফারেন্স উপস্থাপনা দক্ষতা।',
    learn:['Design an A0/A1 research poster','Apply visual hierarchy and white space','Summarize findings in a 3-minute pitch','Use colour effectively for scientific posters','Prepare for Q&A at poster sessions','Create a digital/ePoster version'],
    learnBn:['A0/A1 গবেষণা পোস্টার ডিজাইন','ভিজ্যুয়াল হায়ারার্কি ও সাদা জায়গার ব্যবহার','৩ মিনিটের পিচে ফলাফল সারসংক্ষেপ','বৈজ্ঞানিক পোস্টারের জন্য রঙের ব্যবহার','পোস্টার সেশনে প্রশ্নের জন্য প্রস্তুতি','ডিজিটাল/ePoster সংস্করণ তৈরি'],
    audience:['Conference participants','Thesis students','All researchers','Communications officers'],
    audienceBn:['কনফারেন্স অংশগ্রহণকারী','থিসিস শিক্ষার্থী','সকল গবেষক','যোগাযোগ কর্মকর্তা'],
    duration:'Half Day', badge:'', rating:'4.6', enrolled:'180+', color:'#2e7d32' },

  { cat:'writing', catLabel:'Writing & Publication', catClass:'cat-writing', icon:'bi-virus',
    title:'Basic Concepts of Epidemiology',
    titleBn:'মহামারীবিদ্যার মৌলিক ধারণা',
    desc:'Disease burden measures, outbreak investigation, epidemiological study types, and surveillance.',
    descBn:'রোগের বোঝা পরিমাপ, প্রাদুর্ভাব তদন্ত, মহামারীবিদ্যামূলক স্টাডি ধরন।',
    learn:['Calculate incidence, prevalence, mortality rates','Understand epidemic curves and outbreak investigation','Describe screening tests (sensitivity, specificity)','Distinguish descriptive and analytical epidemiology','Interpret odds ratios and relative risks','Use epidemiological evidence in public health decisions'],
    learnBn:['ইনসিডেন্স, প্রিভালেন্স, মৃত্যুহার গণনা','মহামারী বক্ররেখা ও প্রাদুর্ভাব তদন্ত','স্ক্রিনিং পরীক্ষা বোঝা (সংবেদনশীলতা, নির্দিষ্টতা)','বর্ণনামূলক ও বিশ্লেষণাত্মক মহামারীবিদ্যা','অডস রেশিও ও আপেক্ষিক ঝুঁকি ব্যাখ্যা','জনস্বাস্থ্য সিদ্ধান্তে মহামারীবিদ্যার প্রমাণ ব্যবহার'],
    audience:['Public health students & professionals','Clinicians in community health','Disease surveillance officers','NGO health staff'],
    audienceBn:['জনস্বাস্থ্য শিক্ষার্থী ও পেশাদার','কমিউনিটি স্বাস্থ্যে চিকিৎসক','রোগ নজরদারি কর্মকর্তা','NGO স্বাস্থ্য কর্মী'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'270+', color:'#2e7d32' },

  // ── MANAGEMENT ────────────────────────────────────────────────────────
  { cat:'management', catLabel:'Management', catClass:'cat-management', icon:'bi-kanban',
    title:'Project Management',
    titleBn:'প্রকল্প ব্যবস্থাপনা',
    desc:'Project lifecycle, Gantt charts, risk management, logical framework, and team coordination.',
    descBn:'প্রকল্পের জীবনচক্র, গ্যান্ট চার্ট, ঝুঁকি ব্যবস্থাপনা এবং লজিক্যাল ফ্রেমওয়ার্ক।',
    learn:['Understand project lifecycle (Initiation to Closure)','Build a logical framework (LogFrame)','Create and manage a Gantt chart','Identify, assess and mitigate project risks','Coordinate and lead project teams','Write project progress reports'],
    learnBn:['প্রকল্পের জীবনচক্র বোঝা','লজিক্যাল ফ্রেমওয়ার্ক (LogFrame) তৈরি','গ্যান্ট চার্ট তৈরি ও ব্যবস্থাপনা','প্রকল্প ঝুঁকি চিহ্নিত ও প্রশমন','প্রকল্প দল সমন্বয়','প্রকল্পের অগ্রগতি প্রতিবেদন লেখা'],
    audience:['NGO project staff','Government health officers','Programme managers','Health development workers'],
    audienceBn:['NGO প্রকল্প কর্মী','সরকারি স্বাস্থ্য কর্মকর্তা','কর্মসূচি ব্যবস্থাপক','স্বাস্থ্য উন্নয়ন কর্মী'],
    duration:'2 Days', badge:'', rating:'4.7', enrolled:'230+', color:'#e65100' },

  { cat:'management', catLabel:'Management', catClass:'cat-management', icon:'bi-cash-coin',
    title:'Financial Management',
    titleBn:'আর্থিক ব্যবস্থাপনা',
    desc:'Budget planning, financial reporting, NGO compliance, donor fund management.',
    descBn:'বাজেট পরিকল্পনা, আর্থিক প্রতিবেদন, NGO সম্মতি এবং ডোনার ফান্ড ব্যবস্থাপনা।',
    learn:['Prepare and manage a project budget','Track expenditures against budget lines','Produce financial reports for donors','Ensure NGO Bureau compliance in Bangladesh','Manage petty cash and procurement','Understand financial auditing requirements'],
    learnBn:['প্রকল্পের বাজেট প্রস্তুত ও ব্যবস্থাপনা','বাজেট লাইনের বিপরীতে ব্যয় ট্র্যাক করা','ডোনারদের জন্য আর্থিক প্রতিবেদন','বাংলাদেশ NGO ব্যুরো সম্মতি নিশ্চিত করা','পেটি ক্যাশ ও প্রকিউরমেন্ট ব্যবস্থাপনা','আর্থিক অডিটিং বোঝা'],
    audience:['Finance & admin officers','NGO accountants','Project managers','Govt. health finance staff'],
    audienceBn:['অর্থ ও প্রশাসন কর্মকর্তা','NGO হিসাবরক্ষক','প্রকল্প ব্যবস্থাপক','সরকারি স্বাস্থ্য অর্থ কর্মী'],
    duration:'1 Day', badge:'', rating:'4.6', enrolled:'190+', color:'#e65100' },

  { cat:'management', catLabel:'Management', catClass:'cat-management', icon:'bi-clipboard2-pulse',
    title:'Monitoring & Evaluation (M&E)',
    titleBn:'মনিটরিং ও মূল্যায়ন (M&E)',
    desc:'M&E frameworks, indicators, data collection for results, and impact assessment.',
    descBn:'M&E ফ্রেমওয়ার্ক, সূচক, ফলাফলের জন্য তথ্য সংগ্রহ এবং প্রভাব মূল্যায়ন।',
    learn:['Develop an M&E plan and results framework','Select SMART indicators (output, outcome, impact)','Design data collection tools for M&E','Conduct process and outcome evaluations','Use DHIS2 / KoBoToolbox for M&E data','Write evaluation reports for donors'],
    learnBn:['M&E পরিকল্পনা ও ফলাফল কাঠামো তৈরি','SMART সূচক নির্বাচন','M&E-এর জন্য ডেটা সংগ্রহ টুল ডিজাইন','প্রক্রিয়া ও ফলাফল মূল্যায়ন','DHIS2 / KoBoToolbox ব্যবহার','ডোনারদের জন্য মূল্যায়ন রিপোর্ট লেখা'],
    audience:['M&E officers & specialists','Programme managers','Donor accountability staff','Development researchers'],
    audienceBn:['M&E কর্মকর্তা ও বিশেষজ্ঞ','কর্মসূচি ব্যবস্থাপক','ডোনার জবাবদিহিতা কর্মী','উন্নয়ন গবেষক'],
    duration:'2 Days', badge:'featured', rating:'4.8', enrolled:'260+', color:'#e65100' },

  { cat:'management', catLabel:'Management', catClass:'cat-management', icon:'bi-building',
    title:'DPP Preparation',
    titleBn:'DPP প্রস্তুতি',
    desc:'Development Project Proforma — Bangladesh government project proposal format and standards.',
    descBn:'ডেভেলপমেন্ট প্রজেক্ট প্রোফর্মা — বাংলাদেশ সরকারের প্রকল্প প্রস্তাব ফরম্যাট।',
    learn:['Understand DPP structure and ECNEC approval process','Fill in DPP sections: objectives, activities, budget','Prepare PCR (Project Completion Report)','Work with IMED monitoring framework','Link DPP to SDGs and Bangladesh 8th Five-Year Plan','Navigate government procurement rules (PPR 2008)'],
    learnBn:['DPP কাঠামো ও ECNEC অনুমোদন প্রক্রিয়া','DPP অধ্যায় পূরণ: উদ্দেশ্য, কার্যক্রম, বাজেট','PCR (প্রকল্প সম্পূর্ণতা রিপোর্ট) প্রস্তুতি','IMED মনিটরিং ফ্রেমওয়ার্কের সাথে কাজ','DPP-কে SDG ও ৮ম পঞ্চবার্ষিক পরিকল্পনার সাথে সংযুক্ত করা','সরকারি প্রকিউরমেন্ট বিধি (PPR 2008) নেভিগেট'],
    audience:['Government health & development officers','Planning commission staff','NGO management','Health ministry staff'],
    audienceBn:['সরকারি স্বাস্থ্য ও উন্নয়ন কর্মকর্তা','পরিকল্পনা কমিশন কর্মী','NGO ব্যবস্থাপনা','স্বাস্থ্য মন্ত্রণালয় কর্মী'],
    duration:'2 Days', badge:'new', rating:'4.8', enrolled:'170+', color:'#e65100' },

  { cat:'management', catLabel:'Management', catClass:'cat-management', icon:'bi-people-fill',
    title:'Stakeholder Mapping & Cost-Benefit Analysis',
    titleBn:'স্টেকহোল্ডার ম্যাপিং ও খরচ-সুবিধা বিশ্লেষণ',
    desc:'Identifying stakeholders, power-interest matrix, economic analysis, and policy advocacy.',
    descBn:'স্টেকহোল্ডার চিহ্নিতকরণ, পাওয়ার-ইন্টারেস্ট ম্যাট্রিক্স এবং অর্থনৈতিক বিশ্লেষণ।',
    learn:['Map stakeholders using power-interest grid','Develop stakeholder engagement strategies','Conduct cost-benefit and cost-effectiveness analysis','Calculate Net Present Value (NPV) for projects','Use stakeholder analysis in policy advocacy','Present findings to decision-makers'],
    learnBn:['পাওয়ার-ইন্টারেস্ট গ্রিড দিয়ে স্টেকহোল্ডার ম্যাপিং','স্টেকহোল্ডার সম্পৃক্ততার কৌশল তৈরি','খরচ-সুবিধা ও খরচ-কার্যকারিতা বিশ্লেষণ','প্রকল্পের জন্য NPV গণনা','নীতি পরামর্শে স্টেকহোল্ডার বিশ্লেষণ','সিদ্ধান্তকর্তাদের কাছে ফলাফল উপস্থাপনা'],
    audience:['Health economists','Programme planners','Policy advocates','Senior management'],
    audienceBn:['স্বাস্থ্য অর্থনীতিবিদ','কর্মসূচি পরিকল্পনাকারী','নীতি পরামর্শদাতা','সিনিয়র ব্যবস্থাপনা'],
    duration:'1 Day', badge:'', rating:'4.7', enrolled:'200+', color:'#e65100' },

  // ── SPECIAL PROGRAMS ─────────────────────────────────────────────────
  { cat:'special', catLabel:'Special Programs', catClass:'cat-special', icon:'bi-mortarboard',
    title:'Research Boot Camp for Grade 11 & 12 Students',
    titleBn:'একাদশ ও দ্বাদশ শ্রেণির জন্য রিসার্চ বুট ক্যাম্প',
    desc:'Extracurricular research literacy program — critical thinking, basic statistics, and mini-project.',
    descBn:'পাঠ্যক্রম বহির্ভূত গবেষণা সাক্ষরতা কার্যক্রম — সমালোচনামূলক চিন্তা ও মিনি-প্রকল্প।',
    learn:['Understand what research is and why it matters','Ask good research questions','Collect simple survey data from peers','Analyse data with basic statistics','Create a poster or infographic of findings','Present research confidently in public'],
    learnBn:['গবেষণা কী এবং কেন গুরুত্বপূর্ণ তা বোঝা','ভালো গবেষণা প্রশ্ন জিজ্ঞাসা করা','সহপাঠীদের কাছ থেকে সমীক্ষা ডেটা সংগ্রহ','মৌলিক পরিসংখ্যান দিয়ে ডেটা বিশ্লেষণ','ফলাফলের পোস্টার বা ইনফোগ্রাফিক তৈরি','জনসমক্ষে আত্মবিশ্বাসের সাথে গবেষণা উপস্থাপনা'],
    audience:['Grade 11 & 12 students','School science clubs','Young researchers','Science fair participants'],
    audienceBn:['একাদশ ও দ্বাদশ শ্রেণির শিক্ষার্থী','বিদ্যালয়ের বিজ্ঞান ক্লাব','তরুণ গবেষক','বিজ্ঞান মেলায় অংশগ্রহণকারী'],
    duration:'3 Days', badge:'featured', rating:'4.9', enrolled:'150+', color:'#c62828' },

  { cat:'special', catLabel:'Special Programs', catClass:'cat-special', icon:'bi-geo-alt',
    title:'Field-Based Training (Day or Residential)',
    titleBn:'ফিল্ড ভিত্তিক প্রশিক্ষণ (দিবা বা আবাসিক)',
    desc:'Immersive hands-on field training combining data collection, community engagement, and applied research.',
    descBn:'ডেটা সংগ্রহ, কমিউনিটি সম্পৃক্ততা এবং প্রায়োগিক গবেষণার সমন্বিত ফিল্ড প্রশিক্ষণ।',
    learn:['Conduct community health assessments in the field','Interview community members using structured tools','Observe and document field conditions','Enter and clean real field data same day','Work in a multidisciplinary team setting','Present field findings to local stakeholders'],
    learnBn:['মাঠে কমিউনিটি স্বাস্থ্য মূল্যায়ন','কাঠামোগত টুল দিয়ে কমিউনিটি সদস্যদের সাক্ষাৎকার','মাঠের পরিস্থিতি পর্যবেক্ষণ ও নথিভুক্ত','একই দিনে প্রকৃত ফিল্ড ডেটা এন্ট্রি ও ক্লিনিং','বহুবিভাগীয় দলে কাজ','স্থানীয় স্টেকহোল্ডারদের কাছে ফিল্ড ফলাফল উপস্থাপনা'],
    audience:['Field research teams','Public health officers','Community health workers','NGO field staff'],
    audienceBn:['ফিল্ড গবেষণা দল','জনস্বাস্থ্য কর্মকর্তা','কমিউনিটি স্বাস্থ্য কর্মী','NGO ফিল্ড কর্মী'],
    duration:'1–5 Days', badge:'popular', rating:'5.0', enrolled:'200+', color:'#c62828' },
];

/* ── COURSE PRICES (BDT) ── index matches COURSES array ──
   [0–6]  Research Methods
   [7–10] Data Analysis
   [11–19] Writing & Publication
   [20–24] Management
   [25–26] Special Programs
*/
var COURSE_PRICES = [
  2500, 2500, 2500, 2500, 2500, 1500, 1500,   // Research Methods (Half Day = 1500, 1 Day = 2500)
  4500, 4500, 4500, 2500,                       // Data Analysis
  2500, 2500, 2500, 4500, 5000, 2500, 4500, 1500, 2500, // Writing & Publication
  4500, 2500, 4500, 5000, 2500,                 // Management
  6000, 5000                                    // Special Programs
];

// Attach prices to COURSES objects
(function(){ COURSES.forEach(function(c,i){ c.price = COURSE_PRICES[i] || 2500; }); })();

